### ISSUE TITLE
questions about DataCite concepts

### ISSUE THREAD

**Issue by graybeal** [fair-data-collective/generic-dataset-metadata-template#12]
### ResourceType vs resourceTypeGeneral
In https://github.com/inveniosoftware/datacite/blob/master/tests/data/include/v4.0/datacite-resourceType-v4.xsd, the following appears:
```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://datacite.org/schema/kernel-4" targetNamespace="http://datacite.org/schema/kernel-4" elementFormDefault="qualified">
  <xs:simpleType name="resourceType" id="resourceType">
    <xs:annotation>
      <xs:documentation>The general type of a resource.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Audiovisual"/>
```
with a list of enumeration values afterwards. Yet in the schema for 4.0 (https://support.datacite.org/docs/schema-40), it clearly indicates that the ResourceTypeGeneral has a controlled list similar to the above, while resourceType is free text. Which is correct?

**Comment by niva83** [comment]
They are two different fields, as we have as well 

resourceTypeCategory ---> ResourceTypeGeneral
resourceTypeDetail ---> resourceType

**Comment by graybeal** [comment]
The problem is there seems to be an inversion in the original specification. So the original spec is problematic, and I'm not sure which one they really intend to hold the controlled terms.

**Comment by niva83** [comment]
I am closing this since #16 is closed.
